### ISSUE TITLE
Update on empty `<seg>` in udpipe output

### ISSUE THREAD

**Issue by hpreki** [hpreki/ParCzech4AT#5]
@matyaskopp Observation/Update:
I had a look at files which only show _one_ validation error - because of empty `<seg/>` 

At least in the 2 files I inspected the empty `<seg>` was due to the fact, that the content of the empty `<seg>` was "swallowed" by its predecessor. I.e. the text in the empty `<seg>` did not disappear, but ended up in a  neighbouring `<seg>`.
The bad news: it seems that this "bad behaviour" of udpipe is connected to "anomalies" in the Text. 
In one case a whole seg consisted of a badly spelled `<seg>28.Punkt</seg>` (no space after "." - thus 1 token - and this whole seg was incorporated into the _following_ `<seg>`) 
In the other case the text ended with   URIS - i.e. (`http://xxxxx.xxxxx`) which seemed to confuse udpipe. 

So it seems that 
* udpipe (or the Lindat service) are sometimes collapsing 2 subsequent  `<seg>` into one - which then leaves one of the originals empty.
* anecdotic evidence seems to suggest that this usually is triggered by "anomalies" in the text. 

So in theory it would be great if udpipe was more robust against such "disturbances" ... on the other hand it probably is good that a validation error is thrown which forces me to have a look at the data (i.e. the error _might_ require intervention on the data-side, not the script side)

**Comment by matyaskopp** [comment]
> - udpipe (or the Lindat service) are sometimes collapsing 2 subsequent <seg> into one - which then leaves one of the originals empty.

Yes, lindat udpipe collapses two adjected paragraphs when it is not sure about sentence segmentation (sentences without interpunction or URLs). I have already reported it here: https://github.com/ufal/udpipe/issues/110, but I believe that it was fixed in my script:
https://github.com/hpreki/ParCzech4AT/blob/3211f4ca6e9fd21bd221017bab3f44fae23c35ca/src/udpipe2/udpipe2.pl#L140-L145
I am checking whether the paragraphs were not changed by detecting `\r\n\r\n` in the middle of sentence:
https://github.com/hpreki/ParCzech4AT/blob/3211f4ca6e9fd21bd221017bab3f44fae23c35ca/src/udpipe2/udpipe2.pl#L236

**Comment by hpreki** [comment]
One of the cases where unitok merged a `<seg>` was something like:
```xml
<seg> 28.Punkt
          </seg>
```

It slipped through your "security gates" _twice_ 

_1st:_ 
This does not check for punktuation at the _end_  but matches it everywhere (there was no `$`)- also in "28.Punkt"
https://github.com/hpreki/ParCzech4AT/blob/2d2f1ac7a1477be59b6ef1ae68223c281b3f4fa6/src/udpipe2/udpipe2.pl#L126-L127
 
_2nd:_
In our sample the following did not match because there is an additional whitspace: 
`SpacesAfter=\s\r\n\r\n|TokenRange...`: 
https://github.com/hpreki/ParCzech4AT/blob/2d2f1ac7a1477be59b6ef1ae68223c281b3f4fa6/src/udpipe2/udpipe2.pl#L236

I fixed the 2 lines and will push the code in a second. 

Preliminary results: at least for my small number of 4 test-files there were no validation errors anymore!

**Comment by matyaskopp** [comment]
> This does not check for punktuation at the end but matches it everywhere (there was no $)- also in "28.Punkt"

good spot

> In our sample the following did not match because there is an additional whitespace:

oh, I don't have leading and tailing spaces in element content. I think it is a mess that shouldn't be in our data. But you are right. 

Adding these "security gates" was a hotfix that I had to do in a different project that contained a bigger mess in data, and I was then overloading the lindat service because udpipe was not able to do a correct sentence segmentation.

**Comment by hpreki** [comment]
@matyaskopp  Update: 
1) re-ran the whole corpus (n=1195 files) with the fixed `udpipe2` . 
Result: 10 faulty files. 
2) re-ran these 10 _without_ `--try2fix-spaces`: 
Result: 3 faulty files. But the only error was "no text allowed here" -- because `udpipe2.pl` is confused   by "non-standard-space" in the TEI. 
I replaced  these (e.g. "narrow non breaking space" ) by "ordinary" spaces and everything went fine.

**Summary**: udpipe2.pl processed _all_ my files without error!
